/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phoenix;

import javax.swing.JFileChooser;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.SystemColor;

/**
 *
 * @author
 */
public class PathScreen extends javax.swing.JFrame {

    /**
     * Creates new form Screen4
     */
    String insFile;
    String courseFile;
    DisplayManager dm;
    public PathScreen() {
    	setTitle("AUTOMATIC TIME TABLING SYSTEM");
        initComponents();
    }
    public PathScreen(DisplayManager d) {
        dm=d;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        attachins = new javax.swing.JButton();
        attachcourses = new javax.swing.JButton();
        attachrooms = new javax.swing.JButton();
        attachtimeslots = new javax.swing.JButton();
        attachsections = new javax.swing.JButton();
        instructorspath = new javax.swing.JTextField();
        coursespath = new javax.swing.JTextField();
        roomspath = new javax.swing.JTextField();
        timeslotspath = new javax.swing.JTextField();
        sectionspath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(47, 79, 79));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new Color(0, 204, 255));
        jLabel2.setText("UPLOAD YOUR FILES");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(0, 204, 255));
        jLabel3.setText("INSTRUCTORS");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new Color(0, 204, 255));
        jLabel4.setText("COURSES");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new Color(0, 204, 255));
        jLabel5.setText("ROOMS");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new Color(0, 204, 255));
        jLabel6.setText("TIMESLOTS");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new Color(0, 204, 255));
        jLabel7.setText("SECTIONS");

        submit.setBackground(SystemColor.inactiveCaptionBorder);
        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setForeground(new Color(0, 204, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setBackground(SystemColor.inactiveCaptionBorder);
        cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancel.setForeground(new Color(0, 204, 255));
        cancel.setText("BACK");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        attachins.setBackground(SystemColor.inactiveCaptionBorder);
        attachins.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attachins.setForeground(new Color(0, 204, 255));
        attachins.setText("UPLOAD");
        attachins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachinsActionPerformed(evt);
            }
        });

        attachcourses.setBackground(SystemColor.inactiveCaptionBorder);
        attachcourses.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attachcourses.setForeground(new Color(0, 204, 255));
        attachcourses.setText("UPLOAD");
        attachcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachcoursesActionPerformed(evt);
            }
        });

        attachrooms.setBackground(SystemColor.inactiveCaptionBorder);
        attachrooms.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attachrooms.setForeground(new Color(0, 204, 255));
        attachrooms.setText("UPLOAD");
        attachrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachroomsActionPerformed(evt);
            }
        });

        attachtimeslots.setBackground(SystemColor.inactiveCaptionBorder);
        attachtimeslots.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attachtimeslots.setForeground(new Color(0, 204, 255));
        attachtimeslots.setText("UPLOAD");
        attachtimeslots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachtimeslotsActionPerformed(evt);
            }
        });

        attachsections.setBackground(SystemColor.inactiveCaptionBorder);
        attachsections.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attachsections.setForeground(new Color(0, 204, 255));
        attachsections.setText("UPLOAD");
        attachsections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachsectionsActionPerformed(evt);
            }
        });

        coursespath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursespathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(attachins, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(attachcourses, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(attachrooms, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(attachtimeslots, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(submit, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(attachsections, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(coursespath)
        						.addComponent(instructorspath)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(roomspath)
        							.addComponent(timeslotspath)
        							.addComponent(sectionspath, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cancel)))
        			.addContainerGap(38, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap(167, Short.MAX_VALUE)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
        			.addGap(139))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        				.addComponent(attachins, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(instructorspath))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addComponent(attachcourses))
        				.addComponent(coursespath, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(roomspath, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        					.addComponent(attachrooms))
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(attachtimeslots)
        				.addComponent(timeslotspath, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(sectionspath, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addComponent(attachsections)))
        			.addGap(35)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(submit)
        				.addComponent(cancel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
    	 dm.load(dm);
         this.setVisible(false);
        
    }//GEN-LAST:event_cancelActionPerformed

    private void coursespathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursespathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursespathActionPerformed

    private void attachinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachinsActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        instructorspath.setText(ch.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_attachinsActionPerformed

    private void attachcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachcoursesActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        coursespath.setText(ch.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_attachcoursesActionPerformed

    private void attachroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachroomsActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        roomspath.setText(ch.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_attachroomsActionPerformed

    private void attachtimeslotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachtimeslotsActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        timeslotspath.setText(ch.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_attachtimeslotsActionPerformed

    private void attachsectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachsectionsActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        sectionspath.setText(ch.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_attachsectionsActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        dm.setTimeTable(dm);
        this.setVisible(false);
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PathScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachcourses;
    private javax.swing.JButton attachins;
    private javax.swing.JButton attachrooms;
    private javax.swing.JButton attachsections;
    private javax.swing.JButton attachtimeslots;
    private javax.swing.JButton cancel;
    public javax.swing.JTextField coursespath;
    public javax.swing.JTextField instructorspath;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField roomspath;
    public javax.swing.JTextField sectionspath;
    public javax.swing.JButton submit;
    public javax.swing.JTextField timeslotspath;
    // End of variables declaration//GEN-END:variables
}
