package phoenix;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JInternalFrame;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author 
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    DisplayManager dm;
    public Welcome() {
    	setTitle("AUTOMATIC TIME TABLING SYSTEM");
        initialise_Components();
    }
    public Welcome(DisplayManager d)
    {
        dm=d;
        initialise_Components();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initialise_Components() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setForeground(java.awt.Color.blue);

        jPanel1.setBackground(new Color(47, 79, 79));

        jLabel1.setFont(new Font("Adobe Garamond Pro", Font.BOLD, 26)); // NOI18N
        jLabel1.setForeground(new Color(0, 204, 255));
        jLabel1.setText("WELCOME TO TIME TABLING SYSTEM");
        
        JLabel label = new JLabel("");
        label.setFont(new Font("Adobe Garamond Pro", Font.BOLD, 25));
        
        JLabel lblNewLabel = new JLabel("OF");
        lblNewLabel.setForeground(new Color(102, 204, 255));
        lblNewLabel.setFont(new Font("Adobe Garamond Pro", Font.BOLD, 25));
        
        JLabel lblNewLabel_1 = new JLabel("INSTITUTE OF ENGINEERING AND MANAGEMENT");
        lblNewLabel_1.setFont(new Font("Adobe Garamond Pro", Font.BOLD, 25));
        lblNewLabel_1.setForeground(new Color(0, 204, 255));
        
        JLabel lblNewLabel_2 = new JLabel("");
        lblNewLabel_2.setIcon(new ImageIcon("C:\\Users\\ANJALI\\Desktop\\java_project\\iem.png"));
        
        JButton proceed = new JButton("PROCEED");
        
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	proceedActionPerformed(evt);
            }

			
        });
        
       
        proceed.setBackground(new Color(47, 79, 79));
        proceed.setForeground(new Color(0, 204, 255));
        proceed.setFont(new Font("Adobe Garamond Pro", Font.BOLD, 25));
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(107)
        			.addComponent(label)
        			.addContainerGap())
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(94)
        			.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(311)
        			.addComponent(lblNewLabel)
        			.addContainerGap(323, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(41, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_1)
        			.addGap(38))
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(244)
        			.addComponent(lblNewLabel_2)
        			.addContainerGap(377, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(268)
        			.addComponent(proceed)
        			.addContainerGap(464, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(29)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(15)
        			.addComponent(lblNewLabel)
        			.addGap(18)
        			.addComponent(label)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblNewLabel_1)
        			.addGap(30)
        			.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(proceed)
        			.addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void proceedActionPerformed(ActionEvent evt) {
		dm.setPathScreen(dm);
        this.setVisible(false);
		
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
}
